### PR TITLE
msdk: Refact encoder and vpp

### PR DESCRIPTION
**Pull request by mengker33**

### CODE REVIEW

**Comment by mengker33** [comment]
@xhaihao , @HeJunyan , @xuguangxin, @tong1wu, please help to review. THANKS!

**Comment by xuguangxin** [comment]
Hi Mengke,
thank you for your patches
it's hard to review for .patch. could you help submit your patch to https://github.com/intel-media-ci/gstreamer?

thank you

**Comment by mengker33** [comment]
> Hi Mengke, thank you for your patches it's hard to review for .patch. could you help submit your patch to https://github.com/intel-media-ci/gstreamer?
> 
> thank you

Sure, these was a PR in https://github.com/intel-media-ci/gstreamer before. Let me reopen it.

**Comment by uartie** [comment]
Close until review finished

**Comment by mengker33** [comment]
Need to merge these patches here, and reopen it.

**Comment by mengker33** [comment]
@xhaihao, @HeJunyan, @xuguangxin, if no other issues, please approve and merge these patches here. 
Thanks :)

**Review by uartie — CHANGES_REQUESTED** [review]
Please start your patch sequence at 0012.  We already have a 0011 in latest.

**Comment by mengker33** [comment]
> Please start your patch sequence at 0012. We already have a 0011 in latest.

Oh, I didn't notice it. Thank you.

**Pull request merged**
